version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/avios-api-challenge/api-challenge/api-challenge
    
    steps:
      # git pull
      - checkout
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: mvn dependency:go-offline

      - store_artifacts:
          path: target/classes
          destination: avios-api-challenge