# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      AWS_ACCOUNT_ID: "${AWS_ACCOUNT_ID}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - setup_remote_docker

      - run: mvn dependency:go-offline

      - run:
         name: Install pip
         command: |
            sudo apt update
            sudo apt install -y python-pip python-dev
      - run:
          name: Install awscli
          command:
            sudo pip install awscli

      - run:
        command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          command: docker build -t pcs-app:latest .
# Tag it
      - run:
          command: docker tag pcs-app:latest 934897518238.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/pcs-app
# Push to AWS Elastic Container Registry
      - run:
          command: |
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            docker push 934897518238.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/pcs-app
      - run:
          name: Run script
          command: sudo sh ./deploy.sh pcs-app test $AWS_DEFAULT_REGION 934897518238 AKIAJ4JJ7PF26GZST4JA 1ZsCzsQ1Q0PoHGsqGMA2PcYkhnUHTTEdvq3KnYHh

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test