general:
  artifacts:
    - "api-challenge-0.0.1-SNAPSHOT.jar"
machine:
  java:
    version: oraclejdk8
dependencies:
  override:
    - sudo pip install --upgrade pip
    - sudo pip install awscli
    - mvn dependency:resolve
test:
  override:
    - mvn integration-test
deployment:
  release:
    branch: master
    commands:
      - mvn package
      - aws --version
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region us-east-1
      - aws s3 cp api-challenge-0.0.1-SNAPSHOT.jar s3://spring-boot-sample-bucket/