package com.service.parentalcontrol.hamza;

import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.service.parentalcontrol.hamza.config.DynamoDbConfig;
import com.service.parentalcontrol.hamza.exception.TechnicalFailureException;
import com.service.parentalcontrol.hamza.exception.TitleNotFoundException;
import com.service.parentalcontrol.hamza.impl.MovieServiceImpl;
import com.service.parentalcontrol.hamza.model.MovieClassification;
import com.service.parentalcontrol.hamza.repository.DynamoDbRepository;
import com.service.parentalcontrol.hamza.service.MovieService;
import com.service.parentalcontrol.hamza.impl.ParentalControlServiceImpl;
import com.service.parentalcontrol.hamza.service.ParentalControlService;
import org.junit.Test;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.Spy;
import org.mockito.junit.MockitoJUnitRunner;


import static junit.framework.TestCase.assertTrue;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
import static org.mockito.Mockito.when;
import static org.mockito.ArgumentMatchers.anyString;
import org.junit.Before;
import org.springframework.beans.factory.annotation.Autowired;
import com.amazonaws.services.dynamodbv2.*;
import com.amazonaws.services.dynamodbv2.model.CreateTableRequest;
import org.apache.catalina.core.ApplicationContext;
import org.socialsignin.spring.data.dynamodb.core.DynamoDBTemplate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.test.context.TestPropertySource;
import com.amazonaws.services.dynamodbv2.model.ProvisionedThroughput;
import java.util.List;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
import static org.hamcrest.CoreMatchers.is;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.context.annotation.Configuration;
import org.springframework.test.context.junit4.SpringRunner;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.junit.platform.commons.logging.LoggerFactory;
import org.junit.platform.commons.logging.Logger;
import static org.hamcrest.CoreMatchers.equalTo;
import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(MockitoExtension.class)
@SpringBootTest()
public class ParentalControlServiceTest {

    private MovieService movieService;

    private ParentalControlService pcs;

    @InjectMocks
    private ParentalControlServiceImpl impl;

    @Mock
    private DynamoDBMapper mapper;

    @Mock
    private DynamoDbConfig config;

    @Mock
    private AmazonDynamoDB amazonDynamoDB;

    private final Logger logger = LoggerFactory.getLogger(getClass());
    @Test
    public void contextLoads() {
    }


    @Before
    public void setup() throws TechnicalFailureException, TitleNotFoundException {
        movieService = mock(MovieService.class, RETURNS_SMART_NULLS);
        pcs = mock(ParentalControlService.class, RETURNS_SMART_NULLS);
    }

    @Test
    public void testCanWatch() throws Exception {
        MovieClassification movie = MovieClassification.builder().movieId("1").identifier("U").build();

        String movieId = movie.getMovieId();
        String userLevel = "U";
        String movieLevel = movie.getIdentifier();

        when(movieService.getParentalControlLevel(movieId)).thenReturn(movieLevel);
        when(pcs.checkParentalControlLevel(movieId, userLevel)).thenReturn(true);
        assertTrue(pcs.checkParentalControlLevel(movieId, userLevel));
    }

    @Test
    public void testCannotWatch() throws Exception {
        MovieClassification movie = MovieClassification.builder().movieId("2").identifier("PG").build();

        String movieId = movie.getMovieId();
        String userLevel = "U";
        String movieLevel = movie.getIdentifier();

        when(movieService.getParentalControlLevel(movieId)).thenReturn(movieLevel);
        when(pcs.checkParentalControlLevel(movieId, userLevel)).thenReturn(false);
        assertFalse(pcs.checkParentalControlLevel(movieId, userLevel));

    }

    @Test(expected=TitleNotFoundException.class)
    public void testMovieNotExist() throws Exception {
        MovieClassification movie = MovieClassification.builder().movieId("6").identifier("U").build();

        String movieId = movie.getMovieId();
        String userLevel = "U";
        String movieLevel = movie.getIdentifier();

        when(movieService.getParentalControlLevel(movieId)).thenReturn(movieLevel);
        when(pcs.checkParentalControlLevel(movieId, userLevel)).thenThrow(TitleNotFoundException.class);
        pcs.checkParentalControlLevel(movieId, userLevel);

    }

    @Test(expected=TechnicalFailureException.class)
    public void testSystemError() throws Exception {
        MovieClassification movie = MovieClassification.builder().movieId("1").identifier("U").build();

        String movieId = movie.getMovieId();
        String userLevel = "***";
        String movieLevel = movie.getIdentifier();

        when(movieService.getParentalControlLevel(movieId)).thenReturn(movieLevel);
        when(pcs.checkParentalControlLevel(movieId, userLevel)).thenThrow(TechnicalFailureException.class);
        pcs.checkParentalControlLevel(movieId, userLevel);

    }


}