amazon:
  access:
    key: 'AKIAJ4AAES5ORW6MRSAA'
    secret-key: '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'
  region: us-east-1
  end-point:
    url: dynamodb.us-east-1.amazonaws.com
server:
  port: 8080

spring:
  application:
    name: movies